### ISSUE TITLE
Add 404 page for the site

### ISSUE THREAD

**Issue by mjvbz** [itsMeShon/website#11]
**Issue Type: Feature request**

1. Open this link in the browser - https://mjvbz.github.io/RandomPage ( a random page )
2.  Look at the current 404 page shown in that random page.

**Features**

Add a 404 page for the site which is currently github pages custom 404 page. Now days the most of the website has the 404 pages as customly designed by them. So if this website has one 404 page designed that will be good.

**Comment by TomsMater** [comment]
can i design it?

**Comment by TomsMater** [comment]
and please send me the folder in which i should add it

**Comment by mjvbz** [comment]
It can be added through Github's feature for custom 404 page in sites. Read the 404 documentation by github for more info -  https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

You can design the 404 page and add the file in the github repos main folder where package.json files are pushed. 

That can be designed and push to a new branch. Branch name should be Fix-11. And open a pull request on that main branch and i will check and merge it.

Thanks for designing page. @TomsMater

**Comment by mjvbz** [comment]
Current 404 page by Github pages is :

![20211128_174235](https://user-images.githubusercontent.com/91319186/143767220-1c61e5c7-403d-4e6d-94e7-5d15ac382155.png)

Re-design this to a better Design.

**Comment by TomsMater** [comment]
Hi Shon! So i am thinking like i'll make a repo and then put the design in the media/assets/"name of design" , Then you can fork it and use the image and put it wherever you like!
`<h2>

**I want to do it in this way because i wanna create some repos and get some forks**
</h2>
`

**Comment by mjvbz** [comment]
Hmmm k! Thanks!
